springdoc:
  swagger-ui:
    path: /productservice/docs
    url: /productservice/v3/api-docs
  api-docs:
    path: /productservice/v3/api-docs

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest